### ISSUE TITLE
Regression on OS X in 2.1.0

### ISSUE THREAD

**Issue by RoboticCheese** [chef/mixlib-shellout#100] opened 2015-07-23 16:00 UTC
Hi!

I recently noticed an odd new behavior in mixlib-shellout on OS X and eventually traced it back to a place a bit out of my depth and [this change](https://github.com/chef/mixlib-shellout/commit/765ffc8047b8f7c83d386150c3c8eab3f438e9a1#diff-ad684ea44a04ba1763d515eb5e7a374aR325) that was released in 2.1.0.

In OS X (10.10.5 if it makes a difference), the shell out to `hdiutil attach` in the [dmg cookbook](https://github.com/opscode-cookbooks/dmg/blob/master/providers/package.rb#L54) no longer works, always exiting with status 1.

As easy-ish demonstration, download a .dmg package...

```
wget -P /tmp/ https://steamcdn-a.akamaihd.net/client/installer/steam.dmg
```

...and try to mount it with a shell out to hdiutil...

```
require 'mixlib/shellout'

sh = Mixlib::ShellOut.new("echo Y | PAGER=true hdiutil attach '/tmp/steam.dmg' -quiet")
sh.run_command
sh.error!
puts sh.stdout
```

This code fails under 2.1.0, but works under 2.0.1 or if you just change `Process.setsid` back to `Process.setpgrp`. 

Oddly, it passes in 2.1.0 if the `-quiet` at the end is removed. According to the hdiutil man page:

```
-quiet   close stdout and stderr, leaving only hdiutil's exit status to indicate success or failure.
            No /dev entries or mount points will be printed.
            -debug and -verbose disable -quiet.
```

Anyone with more experience with this project have any thoughts what might be going on? I can submit a tiny patch to the dmg cookbook and move along, but wanted to let folks know in case this is really a larger problem than just that use case.

Thanks!

**Comment by lamont-granquist** [comment] 2015-10-20 17:06
Yeah we use setsid to abandon the controlling tty.

This is correct behavior in most cases.  If someone wants to contribute a switch to turn this off we could consider it, but this is absolutely not a regression that we can revert, this is desired behavior.

The problem is likely that hdiutil is changing behavior when the tty is dropped and the pipe to stdin then 'breaks', which I'd largely blame on hdiutil.  The fact that you're using shell_out to pass PAGER=true into the hdiutil process is quite a bit of lolwut which suggests that hdiutil is behaving extremely non-Unix-ey.

So, the correct fix I'd say would be to the dmg cookbook.

Going to close this now.  If this bites anyone else it could get re-opened, although what I'd like to see there is a flag to change the behavior and switch between setsid and setpgrp behaviors (and the default MUST be setsid for backcompat and general sanity).

**Closed by lamont-granquist** 2015-10-20 17:06 UTC
